
version: 2

models:
  - name: coal_consumption
    description: "Breakout of coal consumption by location and source"

  - name: electricity_breakout
    description: "Breakout of electricity capability by source"

  - name: electricity_coal
    description: "Electricity capability, derived from coal"

  - name: coal_consumption_versus_capability
    description: "Normalized coal capability to consumption"
